### PR TITLE
ECO-1056 - IE cannot acquire camera

### PR DESCRIPTION
**Pull request by jeffswartz**

### CODE REVIEW

**Comment by jeffswartz** [comment]
@maikthomas Could you look this over? The reason it's failing, I think, is because the `loadModalText()` function in precallController.js is being called before the `user-name-modal` is visible. That function is called as a result of `Modal.show(selector, loadModalText)`, later in the file. But that resolves prior to the resolve in line 53 of modal.js being called. 

(You cannot call OT.initPublisher() in IE when the target element is not visible in the DOM and with some dimensions.)

**Comment by voltrevo** [comment]
Testing this I also realised the installer dialog doesn't show. It looks like you're drawing the homepage ui on top of it?

**Comment by voltrevo** [comment]
On my local set up I'm actually getting a plugin crash after specifying the room name, then at that url every time I visit it just crashes on load. Tried restarting IE same result.

@utkarshkhokhar @jeffswartz can you repro this?

Anyway @rhainer it sounds like @jeffswartz has a solid lead on why this might be failing (plugin's `object` tag not visible). I'm sure @jeffswartz / @maikthomas can resolve this if that's the issue, but it's a bit tricky for me because I've never worked on this app and the plugin is crashing on load which hopefully @utkarshkhokhar can repro and debug. Anyway if fixing the visibility issue doesn't resolve it, I'll be happy to take another look.

**Comment by jeffswartz** [comment]
@maikthomas and @utkarshkhokhar -- I added a time-out (and a `publisher.destroy()` call) before initializing the second publisher (the “room” publisher), and that fixes an issue in which the second publisher fails to acquire the camera.

**Pull request merged**
